// source: VNExpress_selector.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.vnexpress_selector.News', null, global);
goog.exportSymbol('proto.vnexpress_selector.Podcast', null, global);
goog.exportSymbol('proto.vnexpress_selector.Range', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vnexpress_selector.Range = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vnexpress_selector.Range.repeatedFields_, null);
};
goog.inherits(proto.vnexpress_selector.Range, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vnexpress_selector.Range.displayName = 'proto.vnexpress_selector.Range';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vnexpress_selector.News = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vnexpress_selector.News.repeatedFields_, null);
};
goog.inherits(proto.vnexpress_selector.News, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vnexpress_selector.News.displayName = 'proto.vnexpress_selector.News';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vnexpress_selector.Podcast = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vnexpress_selector.Podcast, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vnexpress_selector.Podcast.displayName = 'proto.vnexpress_selector.Podcast';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vnexpress_selector.Range.repeatedFields_ = [1,2,3,4,5,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vnexpress_selector.Range.prototype.toObject = function(opt_includeInstance) {
  return proto.vnexpress_selector.Range.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vnexpress_selector.Range} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vnexpress_selector.Range.toObject = function(includeInstance, msg) {
  var f, obj = {
    mainCategoriesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    subCategoriesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    authorList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    dayList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    timeList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    wholeDay: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    dayComparisorList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    timeComparisor: jspb.Message.getFieldWithDefault(msg, 8, ""),
    limit: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vnexpress_selector.Range}
 */
proto.vnexpress_selector.Range.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vnexpress_selector.Range;
  return proto.vnexpress_selector.Range.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vnexpress_selector.Range} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vnexpress_selector.Range}
 */
proto.vnexpress_selector.Range.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addMainCategories(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addSubCategories(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addAuthor(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addDay(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addTime(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWholeDay(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addDayComparisor(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeComparisor(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vnexpress_selector.Range.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vnexpress_selector.Range.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vnexpress_selector.Range} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vnexpress_selector.Range.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMainCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getSubCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getAuthorList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getDayList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getTimeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getWholeDay();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDayComparisorList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getTimeComparisor();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getLimit();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * repeated string main_categories = 1;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.Range.prototype.getMainCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setMainCategoriesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.addMainCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.clearMainCategoriesList = function() {
  return this.setMainCategoriesList([]);
};


/**
 * repeated string sub_categories = 2;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.Range.prototype.getSubCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setSubCategoriesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.addSubCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.clearSubCategoriesList = function() {
  return this.setSubCategoriesList([]);
};


/**
 * repeated string author = 3;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.Range.prototype.getAuthorList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setAuthorList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.addAuthor = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.clearAuthorList = function() {
  return this.setAuthorList([]);
};


/**
 * repeated string day = 4;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.Range.prototype.getDayList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setDayList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.addDay = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.clearDayList = function() {
  return this.setDayList([]);
};


/**
 * repeated string time = 5;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.Range.prototype.getTimeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setTimeList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.addTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.clearTimeList = function() {
  return this.setTimeList([]);
};


/**
 * optional bool whole_day = 6;
 * @return {boolean}
 */
proto.vnexpress_selector.Range.prototype.getWholeDay = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setWholeDay = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * repeated string day_comparisor = 7;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.Range.prototype.getDayComparisorList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setDayComparisorList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.addDayComparisor = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.clearDayComparisorList = function() {
  return this.setDayComparisorList([]);
};


/**
 * optional string time_comparisor = 8;
 * @return {string}
 */
proto.vnexpress_selector.Range.prototype.getTimeComparisor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setTimeComparisor = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string limit = 9;
 * @return {string}
 */
proto.vnexpress_selector.Range.prototype.getLimit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Range} returns this
 */
proto.vnexpress_selector.Range.prototype.setLimit = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vnexpress_selector.News.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vnexpress_selector.News.prototype.toObject = function(opt_includeInstance) {
  return proto.vnexpress_selector.News.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vnexpress_selector.News} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vnexpress_selector.News.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mainCategory: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subCategory: jspb.Message.getFieldWithDefault(msg, 3, ""),
    title: jspb.Message.getFieldWithDefault(msg, 4, ""),
    day: jspb.Message.getFieldWithDefault(msg, 5, ""),
    time: jspb.Message.getFieldWithDefault(msg, 6, ""),
    timeZone: jspb.Message.getFieldWithDefault(msg, 7, ""),
    description: jspb.Message.getFieldWithDefault(msg, 8, ""),
    newsContent: jspb.Message.getFieldWithDefault(msg, 9, ""),
    relatingImageList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    author: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vnexpress_selector.News}
 */
proto.vnexpress_selector.News.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vnexpress_selector.News;
  return proto.vnexpress_selector.News.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vnexpress_selector.News} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vnexpress_selector.News}
 */
proto.vnexpress_selector.News.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainCategory(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubCategory(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDay(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTime(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeZone(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewsContent(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addRelatingImage(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vnexpress_selector.News.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vnexpress_selector.News.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vnexpress_selector.News} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vnexpress_selector.News.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMainCategory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubCategory();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDay();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTime();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTimeZone();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getNewsContent();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getRelatingImageList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string main_category = 2;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getMainCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setMainCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string sub_category = 3;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getSubCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setSubCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string day = 5;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getDay = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setDay = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string time = 6;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setTime = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string time_zone = 7;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getTimeZone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setTimeZone = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string description = 8;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string news_content = 9;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getNewsContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setNewsContent = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * repeated string relating_image = 10;
 * @return {!Array<string>}
 */
proto.vnexpress_selector.News.prototype.getRelatingImageList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setRelatingImageList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.addRelatingImage = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.clearRelatingImageList = function() {
  return this.setRelatingImageList([]);
};


/**
 * optional string author = 11;
 * @return {string}
 */
proto.vnexpress_selector.News.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.News} returns this
 */
proto.vnexpress_selector.News.prototype.setAuthor = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vnexpress_selector.Podcast.prototype.toObject = function(opt_includeInstance) {
  return proto.vnexpress_selector.Podcast.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vnexpress_selector.Podcast} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vnexpress_selector.Podcast.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mainCategory: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subCategory: jspb.Message.getFieldWithDefault(msg, 3, ""),
    title: jspb.Message.getFieldWithDefault(msg, 4, ""),
    day: jspb.Message.getFieldWithDefault(msg, 5, ""),
    time: jspb.Message.getFieldWithDefault(msg, 6, ""),
    timeZone: jspb.Message.getFieldWithDefault(msg, 7, ""),
    description: jspb.Message.getFieldWithDefault(msg, 8, ""),
    relatingPodcast: jspb.Message.getFieldWithDefault(msg, 9, ""),
    author: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vnexpress_selector.Podcast}
 */
proto.vnexpress_selector.Podcast.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vnexpress_selector.Podcast;
  return proto.vnexpress_selector.Podcast.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vnexpress_selector.Podcast} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vnexpress_selector.Podcast}
 */
proto.vnexpress_selector.Podcast.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainCategory(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubCategory(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDay(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTime(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeZone(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setRelatingPodcast(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vnexpress_selector.Podcast.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vnexpress_selector.Podcast.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vnexpress_selector.Podcast} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vnexpress_selector.Podcast.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMainCategory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubCategory();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDay();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTime();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTimeZone();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRelatingPodcast();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string main_category = 2;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getMainCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setMainCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string sub_category = 3;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getSubCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setSubCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string day = 5;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getDay = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setDay = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string time = 6;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setTime = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string time_zone = 7;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getTimeZone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setTimeZone = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string description = 8;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string relating_podcast = 9;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getRelatingPodcast = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setRelatingPodcast = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string author = 10;
 * @return {string}
 */
proto.vnexpress_selector.Podcast.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.vnexpress_selector.Podcast} returns this
 */
proto.vnexpress_selector.Podcast.prototype.setAuthor = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


goog.object.extend(exports, proto.vnexpress_selector);
